const ROOT = document.getElementById('render-area');
const LOADER = document.getElementById('exportLoader');
const SAFE_HEIGHT = 880;
let pageNum = 0;
let currentContainer = null;
let currentH = 0;

const escapeHTML = (value) => String(value || '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#39;');

function addPage(dateLabel) {
  pageNum++;
  const page = document.createElement('div');
  page.className = 'sheet';
  page.innerHTML = `
    <div class="header">
      <div class="brand"><i class="fas fa-brain"></i> ZEPRA MEMORY</div>
      <div class="meta-date">
        CONFIDENTIAL<br>
        ${dateLabel}
      </div>
    </div>
    <div class="content"></div>
    <div class="footer">
      <span>Generated by Zepra Core</span>
      <span>Page ${String(pageNum).padStart(2, '0')}</span>
    </div>
  `;
  ROOT.appendChild(page);
  currentContainer = page.querySelector('.content');
  currentH = 0;
}

const measureBox = document.createElement('div');
measureBox.style.cssText = "position:absolute; visibility:hidden; width:180mm; font-family:'Inter', sans-serif;";
document.body.appendChild(measureBox);

function buildInsightText(insight) {
  if (!insight || typeof insight !== 'object') return '';
  const analysis = insight.analysis || insight;
  const signals = Array.isArray(analysis.keySignals) ? analysis.keySignals.join(' â€¢ ') : '';
  return [
    analysis.objective ? `Objective: ${analysis.objective}` : '',
    analysis.targetPersona ? `Target Persona: ${analysis.targetPersona}` : '',
    signals ? `Key Signals: ${signals}` : '',
    analysis.confidence ? `Confidence: ${analysis.confidence}` : ''
  ].filter(Boolean).join('\n');
}

const params = new URLSearchParams(window.location.search);
const exportJobId = params.get('jobId') || '';

async function requestJobPayload() {
  if (!exportJobId || typeof chrome === 'undefined' || !chrome.runtime?.sendMessage) return null;
  return new Promise((resolve) => {
    chrome.runtime.sendMessage({ type: 'EXPORT_PAYLOAD_REQUEST', jobId: exportJobId }, (response) => {
      resolve(response?.payload || null);
    });
  });
}

async function readPayload() {
  const jobPayload = await requestJobPayload();
  if (jobPayload) return jobPayload;
  if (typeof chrome !== 'undefined' && chrome.storage?.local) {
    const { memoryPdfPayload = null } = await chrome.storage.local.get('memoryPdfPayload');
    return memoryPdfPayload;
  }
  return null;
}

async function renderPDF() {
  const memoryPdfPayload = await readPayload();
  const payload = memoryPdfPayload || { entries: [], insight: null };
  const generationDate = payload.exportedAt ? new Date(payload.exportedAt).toLocaleDateString('en-GB') : new Date().toLocaleDateString('en-GB');
  const entries = Array.isArray(payload.entries) ? payload.entries : [];
  const insightText = buildInsightText(payload.insight);

  addPage(generationDate);

  if (insightText) {
    const insHTML = `
      <div class="insight-box">
        <div class="insight-head"><i class="fas fa-chart-line"></i> Survey Intelligence</div>
        <div class="insight-body">${escapeHTML(insightText).replace(/\n/g, '<br>')}</div>
      </div>`;
    measureBox.innerHTML = insHTML;
    let elH = measureBox.offsetHeight + 15;
    const div = document.createElement('div');
    div.innerHTML = insHTML;
    currentContainer.appendChild(div.firstElementChild);
    currentH += elH;
  }

  if (entries.length) {
    entries.forEach((item, idx) => {
      const timeStr = item.ts ? new Date(item.ts).toLocaleString() : (item.time || new Date().toLocaleTimeString());
      const cardHTML = `
        <div class="card">
          <div class="card-meta">
            <span>ENTRY #${String(idx + 1).padStart(3, '0')}</span>
            <span>${escapeHTML(timeStr)}</span>
          </div>
          <div class="q-text">${escapeHTML(item.q)}</div>
          <div class="a-text">${escapeHTML(item.a)}</div>
        </div>`;

      measureBox.innerHTML = cardHTML;
      const elH = measureBox.offsetHeight + 12;

      if (currentH + elH > SAFE_HEIGHT) {
        addPage(generationDate);
      }

      const wrapper = document.createElement('div');
      wrapper.innerHTML = cardHTML;
      currentContainer.appendChild(wrapper.firstElementChild);
      currentH += elH;
    });
  } else {
    const emptyHTML = `<div style="text-align:center; color:#555; padding:20px;">No memory entries found.</div>`;
    currentContainer.innerHTML += emptyHTML;
  }

  if (LOADER) LOADER.style.display = 'none';
}

async function notifyRendered() {
  if (!exportJobId || typeof chrome === 'undefined' || !chrome.runtime?.sendMessage) return;
  if (document.fonts?.ready) {
    await document.fonts.ready.catch(() => {});
  }
  await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
  chrome.runtime.sendMessage({ type: 'EXPORT_RENDERED', jobId: exportJobId });
}

renderPDF().then(notifyRendered);
